### ISSUE TITLE
Adapter for ZKInterface

### ISSUE THREAD

**Issue by Tails** [microsoft/Spartan#23]
A nice interface layer has been developed that loosely connects R1CS frontends with backends. It would be great if Spartan would have an adapter to plug into ZKInterface, so circuits could easily be defined in a frontend tool, such as ZoKrates or others.

https://medium.com/@gokulbabyalex/zkinterface-an-emerging-standard-for-zero-knowledge-frameworks-93e02bcd664d

https://github.com/QED-it/zkinterface

**Comment by srinathsetty** [comment]
Yes, that would be fantastic! As mentioned in #22 we will add public APIs to create objects of type R1CSInstance. I think it should be easy to add an adapter from ZKInterface to R1CSInstance.

**Comment by srinathsetty** [comment]
Closing this issue for now. We have added new APIs that can be used to specify any externally-generated R1CS including zkinterface. To keep the library footprint small, we expose a low-level API, but one can build an adapter from zkinterface to our low-level interface.
