### ISSUE TITLE
Add another challenge in dotproduct proof?

### ISSUE THREAD

**Issue by 3for** [microsoft/Spartan#33]
In paper [Halo: Recursive Proof Composition without a Trusted Setup ](https://eprint.iacr.org/2019/1021.pdf), section 3.1:
![image](https://user-images.githubusercontent.com/30716372/104806100-fb5f1b80-580f-11eb-9b53-f7cee986159a.png)

And in paper [Bulletproofs: Short Proofs for Confidential Transactions and More](https://eprint.iacr.org/2017/1066.pdf), protocol 1:
![image](https://user-images.githubusercontent.com/30716372/104806159-542eb400-5810-11eb-9eb5-c3a9118a7724.png)

Do we need to add another challenge `x` in `DotProductProofLog` and `DotProductProofLog`, as shown above, to avoid the Prover cheat?

**Comment by srinathsetty** [comment]
@3for Thanks for bringing this to my attention! I checked with the authors of [37] and indeed, we need to add the additional challenge.

**Comment by 3for** [comment]
Glad to help~
