### ISSUE TITLE
Differences between Spartan and ZkSTARKs

### ISSUE THREAD

**Issue by jochasinga** [microsoft/Spartan#40]
Since ZkSTARKS is also transparent and does not require a trusted setup, a documentation outlining Spartan works in general and how it's different from the first can be really helpful for users.

**Comment by AtropineTears** [comment]
ZKStarks is post-quantum and is built on the security assumption of Hash Functions. Spartan is not post-quantum secure as it uses discrete logarithm for its security assumption.

Both are transparent in that they both do not require a trusted setup.

Spartan has much smaller proofs than STARKs.

You can read the paper [here](https://eprint.iacr.org/2019/550)

**Comment by srinathsetty** [comment]
Thanks, @AtropineTears.  

@jochasinga I would also add that Spartan provides sub-linear verification costs even when the circuit is *not* uniform. Whereas, STARKs provide sub-linear verification costs only for uniform/regular circuits (i.e., circuits with repeated sub-circuits).
