### ISSUE TITLE
How Do I Construct R1CS Using Negative Values?

### ISSUE THREAD

**Issue by AtropineTears** [microsoft/Spartan#43]
Hi,

I am looking to construct a R1CS but need some help. I would like to know how I can use a negative value for the R1CS like it says in this [blog post](https://blog.decentriq.com/zk-snarks-primer-part-one/). They use x<sup>2</sup> - 4 but i do not know how to make an R1CS Circuit with negative numbers.

I would really appreciate some help with a few other things too.

Thank you.

**Comment by srinathsetty** [comment]
Hi @AtropineTears For -4, you can use p - 4 where p = 2^{252}+27742317777372353535851937790883648493 (the prime field in the scalar field of Ristretto/Curve25519). Does this help?

**Comment by srinathsetty** [comment]
Closing the issue for now. Please reopen if the above does not work.
