### ISSUE TITLE
Converting Spartan to Wasm

### ISSUE THREAD

**Issue by natalialinov** [microsoft/Spartan#54]
Hi, is it possible to convert Spartan to wasm? I want to convert Spartan to WASM and use it in every platform.

**Comment by srinathsetty** [comment]
@natalialinov I think it is possible since there are minimal dependencies and they all should support running them in wasm. We haven't tried doing it though.

**Comment by srinathsetty** [comment]
Thanks to @ashutoshvarma's PR #60, we have better support for WASM. We just published a new version of the crate: https://crates.io/crates/spartan
