### ISSUE TITLE
Proving math functions with Spartan

### ISSUE THREAD

**Issue by Fobow** [microsoft/Spartan#67]
Thanks for your great work.
I wonder if it is possible to prove math functions such as simple comparison, square root, reciprocal or (more complex) exponential functions using Spartan. Could you shed some light on this? Thanks a lot!

**Comment by Fobow** [comment]
I think the challenge is expressing these non-linear computations in R1CS?

**Comment by srinathsetty** [comment]
Yes, exactly. There are tools like circom and noir that can let you express high-level computation and they can then be proven with spartan.
