### ISSUE TITLE
R1CS instance does not match the definition

### ISSUE THREAD

**Issue by ishwarbb** [microsoft/Spartan#69]
The R1CS instance example used in cubic.rs is not an R1CS instance according to [https://eprint.iacr.org/2020/1069.pdf](link)  Theorem 19 . Although it's still a valid constraint system, it's just more inefficient

![image](https://github.com/microsoft/Spartan/assets/95575080/f35c5f0a-9f17-4e78-954a-32d3d8766fb8)

 We need total constraints to be No.of Multiplication gates + 1. The last constraint handles all additions  and Basically the last two constraints can be combined into one addition constraint.

**Comment by srinathsetty** [comment]
Thanks for the note! Yes, cubic.rs is just an example. Please feel free to submit a PR.
