### ISSUE TITLE
Possible Mistake in Assert Statement

### ISSUE THREAD

**Issue by ishwarbb** [microsoft/Spartan#70]
`src/sparse_mlpoly.rs` - line 1265 has the following code -
```
assert_eq!(eval_dotp_left.len(), eval_dotp_left.len());
```

Was this the intended behavior? Did the authors mean this instead - 
```
assert_eq!(eval_dotp_left.len(), eval_dotp_right.len());
```

**Comment by srinathsetty** [comment]
Thanks for the catch! Yes, indeed the assert is what you noted in the last line. It is not critical for correctness, but it should be fixed.
